package ruslan.token;

public enum TokenTypes {
    KEYWORD,
    ASSIGN_OPERATION,
    DOT,
    SPACE,
    NEW_LINE,
    ADDITION_OPERATION,
    MULTIPLICATION_OPERATION,
    L_PARENTHESIS_OPERATION,
    R_PARENTHESIS_OPERATION,
    POW_OPERATION,
    RELATIVE_OPERATION,
    IDENTIFIER,
    DOUBLE,
    INT,
    BOOLEAN,
    PUNCTUATION,
    OTHER
}
